version: "3.8"

services:
  api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bharatFd
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - ACCESS_TOKEN_SECRET=your_access_token_secret
      - ACCESS_TOKEN_EXPIRES_IN=15m
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - PORT=3000
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
